/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Hide Toolbar",
  "description": "The toolbar will hidden and can automatically appear when you hover nearby. You may also choose to lock it in place for persistent display.",
  "tags": ['theme',"astraeditor"],
  "credits": [
    {
      "name": "KOSHINO",
      "link": "https://github.com/KOSHINOawa"
    },
    {
      "name": "RyaninCn11",
      "link": "https://github.com/RyaninCn11"
    }
  ],
  "enabledByDefault": false,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ]
};
export default manifest;
