onlyBuiltDependencies:
  - chromedriver
  - fsevents
  - 'scratch-blocks@git+https://github.com/PYC5635/scratch-blocks.git#c853a27bc5d46cd6f83cc4fe72f7b57b845ac693'
  - 'scratch-audio@git+https://github.com/PYC5635/scratch-audio.git#35f794710dd38616b9a02a0ca5f21969575cc037'
  - 'scratch-paint@git+https://github.com/PYC5635/scratch-paint.git#01029209005aa1cff1ca8f73e65eb8b6d5b42536'
  - 'scratch-render@git+https://github.com/PYC5635/scratch-render.git#01df30f4b76108581bb0add8eded502bb07ecb11'
  - 'scratch-vm@git+https://github.com/PYC5635/scratch-vm.git#33e550cc5c40ead082f01f4d4bfbe775898ad377'
  - 'scratch-parser@git+https://github.com/PYC5635/scratch-parser.git#2517e6e8206e8c48bbe09b551c4b3a4495427abe'
  - '@bilup/scratch-l10n@git+https://github.com/PYC5635/scratch-l10n.git#76904641febda9375cad4d0ffd8ab8db611d53d6'
  - '@bilup/scratch-storage@git+https://github.com/PYC5635/scratch-storage.git#57d0d7aa3f54d7993e269e597e8e5051e3183258'
  - '@bilup/scratch-svg-renderer@git+https://github.com/PYC5635/scratch-svg-renderer.git#d19dab859b080afc5d981b3c6b13076376b668fa'
  - 'rotur-sdk@git+https://github.com/PYC5635/accounts-sdk.git#718dab813dec7bd9f28700015d8e432e5c4b0e78'

blockExoticSubdeps: false
strictDepBuilds: false

allowBuilds:
  scratch-blocks@git+https://github.com/PYC5635/scratch-blocks.git: true
  scratch-audio@git+https://github.com/PYC5635/scratch-audio.git: true
  scratch-paint@git+https://github.com/PYC5635/scratch-paint.git: true
  scratch-render@git+https://github.com/PYC5635/scratch-render.git: true
  scratch-vm@git+https://github.com/PYC5635/scratch-vm.git: true
  '@bilup/scratch-l10n@git+https://github.com/PYC5635/scratch-l10n.git': true
  '@bilup/scratch-storage@git+https://github.com/PYC5635/scratch-storage.git': true
  scratch-parser@git+https://github.com/PYC5635/scratch-parser.git: true
  '@bilup/scratch-svg-renderer@git+https://github.com/PYC5635/scratch-svg-renderer.git': true
  rotur-sdk@git+https://github.com/PYC5635/accounts-sdk.git: true

overrides:
  webpack@4.47.0>terser-webpack-plugin: ^1.4.1
  cheerio: 1.0.0-rc.12
  brace-expansion: 1.1.11
  rotur-sdk: github:PYC5635/accounts-sdk#main
  escape-string-regexp: 4.0.0
