/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Project Size Display",
  "description": "Displays project size, block count, and selected sprite/stage size at the bottom of the sprite selector.",
  "tags": ["new"],
  "credits": [
    {
      "name": "DL_Grass",
      "link": 'https://github.com/DLGrass/'
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "enabledByDefault": true
};
export default manifest;