/* generated by pull.js */
const manifest = {
  "name": "PineWarp Sample",
  "description": "A sample local plugin demonstrating the bilup-addons pipeline. Shows a message in the stage header and logs it to console.",
  "credits": [
    {
      "name": "PineWarp"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "settings": [
    {
      "id": "message",
      "type": "string",
      "default": "Hello from PineWarp Sample!",
      "name": "Message"
    }
  ],
  "tags": [
    "recommended"
  ],
  "enabledByDefault": false
};
export default manifest;
